export const poiImageMap: Record<string, string[]> = {
  "共乐园": [
    "poi-images/共乐园/caption.jpg",
    "poi-images/共乐园/photo0jpg.jpg",
    "poi-images/共乐园/photo2jpg.jpg",
    "poi-images/共乐园/photo3jpg.jpg",
    "poi-images/共乐园/photo4jpg.jpg",
    "poi-images/共乐园/photo5jpg.jpg",
    "poi-images/共乐园/photo6jpg.jpg",
  ],
  "北山": [
    "poi-images/北山/-UFyhWQqS34MnuELODTQ_lzUl2w5oWCXUEo0BgAXbgijCSEcHZIUUdmpUSySIlpOY0q73sB2DyQcgmKUxZFQtw.jpg",
    "poi-images/北山/Cw90IBbVthT2aEfgEUKctucTKKYai5GuFYyPlGnm1zIuaWtodzrOKoh8dma5a1_PY0q73sB2DyQcgmKUxZFQtw.jpg",
    "poi-images/北山/IpEQ61CjUR2LZc_npw0PeCXT57NYFTWla7jvYbLpOszotXZfeh0kV7jeaYGxLTp1Y0q73sB2DyQcgmKUxZFQtw.jpg",
    "poi-images/北山/ZU_YygcjvaC1a5kMHwzKTmCGt8ShKCTYvmjTnlFAr9GJAYtNNOC6Lf1EzNJ6ACEOY0q73sB2DyQcgmKUxZFQtw.jpg",
    "poi-images/北山/jdvIsdVlStJaPcOsigSCtFORmAI-ytAkufS5pEpUVz9zTIfTdPfs0fOyzV3vkEcFY0q73sB2DyQcgmKUxZFQtw.jpg",
    "poi-images/北山/m3Ehq8pvuE-uOu34zVfPSxdxgOuMydLaoG-7i3-hlils2-S5q3eSnySV4L2X7KjBY0q73sB2DyQcgmKUxZFQtw.jpg",
  ],
  "唐家古镇": [
    "poi-images/唐家古镇/caption (2).jpg",
    "poi-images/唐家古镇/caption.jpg",
  ],
  "圆明新园": [
    "poi-images/圆明新园/lake.jpg",
    "poi-images/圆明新园/map-of-the-new-yuan-ming.jpg",
    "poi-images/圆明新园/one-of-the-hall (1).jpg",
    "poi-images/圆明新园/one-of-the-hall.jpg",
    "poi-images/圆明新园/photo5jpg.jpg",
    "poi-images/圆明新园/photo7jpg.jpg",
  ],
  "富华里": [
    "poi-images/富华里/caption (1).jpg",
    "poi-images/富华里/caption (2).jpg",
    "poi-images/富华里/caption (3).jpg",
    "poi-images/富华里/caption.jpg",
  ],
  "扬名广场": [
    "poi-images/扬名广场/photo1jpg.jpg",
    "poi-images/扬名广场/photo6jpg.jpg",
    "poi-images/扬名广场/photo9jpg.jpg",
  ],
  "景山公园": [
    "poi-images/景山公园/caption (1).jpg",
    "poi-images/景山公园/caption (2).jpg",
    "poi-images/景山公园/caption (3).jpg",
    "poi-images/景山公园/caption (4).jpg",
    "poi-images/景山公园/caption (5).jpg",
    "poi-images/景山公园/caption (6).jpg",
    "poi-images/景山公园/caption.jpg",
    "poi-images/景山公园/love-lock-stone.jpg",
  ],
  "爱情邮局": [
    "poi-images/爱情邮局/caption (1).jpg",
    "poi-images/爱情邮局/caption (2).jpg",
    "poi-images/爱情邮局/caption (3).jpg",
    "poi-images/爱情邮局/caption.jpg",
  ],
  "珠海博物馆": [
    "poi-images/珠海博物馆/an-exhibit.jpg",
    "poi-images/珠海博物馆/caption (1).jpg",
    "poi-images/珠海博物馆/caption.jpg",
    "poi-images/珠海博物馆/zhuhai-museum (1).jpg",
    "poi-images/珠海博物馆/zhuhai-museum-1.jpg",
    "poi-images/珠海博物馆/zhuhai-museum.jpg",
  ],
  "珠海海滨泳场": [
    "poi-images/珠海海滨泳场/caption (1).jpg",
    "poi-images/珠海海滨泳场/caption (2).jpg",
    "poi-images/珠海海滨泳场/caption (3).jpg",
    "poi-images/珠海海滨泳场/caption (4).jpg",
    "poi-images/珠海海滨泳场/caption.jpg",
    "poi-images/珠海海滨泳场/zhuhai-seaside-park.jpg",
  ],
  "石景山公园": [
    "poi-images/石景山公园/the-statue.jpg",
  ],
  "野狸岛": [
    "poi-images/野狸岛/photo1jpg.jpg",
    "poi-images/野狸岛/photo5jpg.jpg",
    "poi-images/野狸岛/photo6jpg.jpg",
  ],
  "香炉湾沙滩": [
    "poi-images/香炉湾沙滩/A6yP0QW8W4HPOIY3n5GKhWX81Nd-I7EoDSVUXUR3AsRanKiGlAgSmuDse6O-eke6Y0q73sB2DyQcgmKUxZFQtw.jpg",
    "poi-images/香炉湾沙滩/dcVOYxp_q3GxMpYex_y5o7BJ-XN50imZmio3DkYgmNCHWNciV-WYU3BPA5hV6m8QY0q73sB2DyQcgmKUxZFQtw.jpg",
  ],
} as const;
